apiVersion: v1
kind: Pod
metadata:
  name: kubegres-file-checker
spec:
  containers:
  - image: busybox
    name: file-checker
    args:
    - /bin/sh
    - -c
    - |
      echo "Looking for '${RESTOREPOINT_FILEPATH}'...";
      if [ ! -f "${RESTOREPOINT_FILEPATH}" ]; then
        ls $(dirname "${RESTOREPOINT_FILEPATH}") -t -p | grep -v / | head -n5 > /dev/termination-log;
        exit 2;
      else exit 0; fi
    volumeMounts:
    - name: backup-volume
      mountPath: toBeReplaced
    resources:
      limits:
        memory: "64Mi"
        cpu: "50m"
    env:
    - name: RESTOREPOINT_FILEPATH
      value: toBeReplaced
  restartPolicy: Never
  volumes:
  - name: backup-volume
    persistentVolumeClaim:
      claimName: toBeReplaced
